openapi: 3.0.3
info:
  title: Obsidion Minecraft API
  description: This is the API developed by the [Obsidion-dev](https://github.com/Obsidion-dev)
    team for use by the minecraft community
  contact:
    name: Developer
    email: leon@bowie-co.nz
  license:
    name: GNU AGPL v3
    url: https://www.gnu.org/licenses/agpl-3.0.html
  version: 1.0.0
servers:
- url: https://api.obsidion-dev.com/v1
  description: Development Server
tags:
- name: server
  description: Information about a minecraft server
- name: mojang
  description: Information about mojang services
- name: images
  description: image generation
- name: info
  description: info about minecraft stuff
- name: render
  description: render items/blocks
- name: servertracking
  description: servertracking
paths:
  /servers/java:
    get:
      tags:
      - server
      description: returns info about a minecraft server
      operationId: servers_java_get
      parameters:
      - name: server
        in: query
        description: ip or hostname of the server
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: port
        in: query
        description: port of the server
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int64
          default: 25565
      responses:
        "200":
          description: server info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
      x-openapi-router-controller: swagger_server.controllers.server_controller
  /server/javaicon:
    get:
      tags:
      - server
      description: generated motd for the server
      operationId: server_javaicon_get
      parameters:
      - name: server
        in: query
        description: ip or hostname of the server
        required: true
        style: form
        explode: true
        schema:
          type: string
          format: int64
      - name: port
        in: query
        description: port of the server
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: server info
          content:
            image/png:
              schema:
                type: string
                format: binary
                x-content-type: image/png
      x-openapi-router-controller: swagger_server.controllers.server_controller
  /servers/bedrock:
    get:
      tags:
      - server
      description: returns info about a minecraft server
      operationId: servers_bedrock_get
      parameters:
      - name: server
        in: query
        description: ip or hostname of the server
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: port
        in: query
        description: port of the server
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int64
          default: 19132
      responses:
        "200":
          description: server info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
      x-openapi-router-controller: swagger_server.controllers.server_controller
  /mojang/check:
    get:
      tags:
      - mojang
      summary: Get information on mojang services
      operationId: mojang_check_get
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
      x-openapi-router-controller: swagger_server.controllers.mojang_controller
  /images/sign:
    get:
      tags:
      - images
      summary: create an sign.png
      operationId: images_sign_get
      parameters:
      - name: wood
        in: query
        description: choose what type of wood the sign should be
        required: false
        style: form
        explode: true
        schema:
          type: string
          default: oak
      - name: line1
        in: query
        description: first line of the sign
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: line2
        in: query
        description: second line of the sign
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: line3
        in: query
        description: third line of the sign
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: line4
        in: query
        description: fourth line of the sign
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            image/png:
              schema:
                type: string
                format: binary
                x-content-type: image/png
      x-openapi-router-controller: swagger_server.controllers.images_controller
  /images/advancement:
    get:
      tags:
      - images
      summary: create a minecraft acheivement
      operationId: images_advancement_get
      parameters:
      - name: item
        in: query
        description: choose what item is shown
        required: false
        style: form
        explode: true
        schema:
          type: string
          default: cake
      - name: title
        in: query
        description: title of acheivement
        required: false
        style: form
        explode: true
        schema:
          type: string
          default: 'Achievement Got:'
      - name: text
        in: query
        description: acheivement text
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            image/png:
              schema:
                type: string
                format: binary
                x-content-type: image/png
      x-openapi-router-controller: swagger_server.controllers.images_controller
  /images/book:
    get:
      tags:
      - images
      summary: create a page from a minecraft book
      operationId: images_book_get
      parameters:
      - name: text
        in: query
        description: text to fill the book
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            image/png:
              schema:
                type: string
                format: binary
                x-content-type: image/png
      x-openapi-router-controller: swagger_server.controllers.images_controller
  /images/death:
    get:
      tags:
      - images
      summary: Create a custom death screen
      operationId: images_death_get
      parameters:
      - name: message
        in: query
        description: death message
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: xp
        in: query
        description: score to show
        required: true
        style: form
        explode: true
        schema:
          type: integer
      responses:
        "200":
          description: successful operation
          content:
            image/png:
              schema:
                type: string
                format: binary
                x-content-type: image/png
      x-openapi-router-controller: swagger_server.controllers.images_controller
  /images/splashscreen:
    get:
      tags:
      - images
      summary: Create a custom minecraft splashscreen
      operationId: images_splashscreen_get
      parameters:
      - name: text
        in: query
        description: text on splashscreen
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            image/png:
              schema:
                type: string
                format: binary
                x-content-type: image/png
      x-openapi-router-controller: swagger_server.controllers.images_controller
  /images/motd:
    get:
      tags:
      - images
      summary: View motd
      operationId: images_motd_get
      parameters:
      - name: text
        in: query
        description: motd text
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            image/png:
              schema:
                type: string
                format: binary
                x-content-type: image/png
      x-openapi-router-controller: swagger_server.controllers.images_controller
  /info/item:
    get:
      tags:
      - info
      summary: info about a minecraft item
      operationId: info_item_get
      parameters:
      - name: name
        in: query
        description: name of item
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Info about an item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_3'
      x-openapi-router-controller: swagger_server.controllers.info_controller
  /info/block:
    get:
      tags:
      - info
      summary: info about a minecraft item
      operationId: info_block_get
      parameters:
      - name: name
        in: query
        description: name of item
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Logo image in PNG format
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.info_controller
  /info/mob:
    get:
      tags:
      - info
      summary: info about a minecraft item
      operationId: info_mob_get
      parameters:
      - name: name
        in: query
        description: name of item
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Logo image in PNG format
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.info_controller
  /info/acheivement:
    get:
      tags:
      - info
      summary: info about a minecraft item
      operationId: info_acheivement_get
      parameters:
      - name: name
        in: query
        description: name of item
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Logo image in PNG format
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.info_controller
  /info/structure:
    get:
      tags:
      - info
      summary: info about a minecraft item
      operationId: info_structure_get
      parameters:
      - name: name
        in: query
        description: name of item
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Logo image in PNG format
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.info_controller
  /info/biome:
    get:
      tags:
      - info
      summary: info about a minecraft item
      operationId: info_biome_get
      parameters:
      - name: name
        in: query
        description: name of item
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Logo image in PNG format
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.info_controller
  /info/command:
    get:
      tags:
      - info
      summary: info about a minecraft item
      operationId: info_command_get
      parameters:
      - name: name
        in: query
        description: name of item
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Logo image in PNG format
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.info_controller
  /info/loottable:
    get:
      tags:
      - info
      summary: info about a minecraft item
      operationId: info_loottable_get
      parameters:
      - name: name
        in: query
        description: name of item
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Logo image in PNG format
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.info_controller
  /render/item:
    get:
      tags:
      - render
      summary: View motd
      operationId: render_item_get
      parameters:
      - name: text
        in: query
        description: motd text
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            image/png:
              schema:
                type: string
                format: binary
                x-content-type: image/png
      x-openapi-router-controller: swagger_server.controllers.render_controller
  /render/mob:
    get:
      tags:
      - render
      summary: View motd
      operationId: render_mob_get
      parameters:
      - name: text
        in: query
        description: motd text
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            image/png:
              schema:
                type: string
                format: binary
                x-content-type: image/png
      x-openapi-router-controller: swagger_server.controllers.render_controller
  /render/recipie:
    get:
      tags:
      - render
      summary: View motd
      operationId: render_recipie_get
      parameters:
      - name: text
        in: query
        description: motd text
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            image/png:
              schema:
                type: string
                format: binary
                x-content-type: image/png
      x-openapi-router-controller: swagger_server.controllers.render_controller
  /render/banner:
    get:
      tags:
      - render
      summary: View motd
      operationId: render_banner_get
      parameters:
      - name: text
        in: query
        description: motd text
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            image/png:
              schema:
                type: string
                format: binary
                x-content-type: image/png
      x-openapi-router-controller: swagger_server.controllers.render_controller
  /render/firework:
    get:
      tags:
      - render
      summary: View motd
      operationId: render_firework_get
      parameters:
      - name: text
        in: query
        description: motd text
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            image/png:
              schema:
                type: string
                format: binary
                x-content-type: image/png
      x-openapi-router-controller: swagger_server.controllers.render_controller
  /strack:
    get:
      tags:
      - servertracking
      summary: info about a minecraft item
      operationId: strack_get
      parameters:
      - name: name
        in: query
        description: name of item
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Logo image in PNG format
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.servertracking_controller
    put:
      tags:
      - servertracking
      summary: info about a minecraft item
      operationId: strack_put
      parameters:
      - name: name
        in: query
        description: name of item
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Logo image in PNG format
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.servertracking_controller
    post:
      tags:
      - servertracking
      summary: info about a minecraft item
      operationId: strack_post
      parameters:
      - name: name
        in: query
        description: name of item
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Logo image in PNG format
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.servertracking_controller
    delete:
      tags:
      - servertracking
      summary: info about a minecraft item
      operationId: strack_delete
      parameters:
      - name: name
        in: query
        description: name of item
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Logo image in PNG format
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.servertracking_controller
components:
  schemas:
    inline_response_200:
      type: object
      properties:
        online:
          type: boolean
        ip:
          type: string
        port:
          type: integer
        debug:
          type: object
          properties:
            ping:
              type: boolean
            query:
              type: boolean
            srv:
              type: boolean
            querymismatch:
              type: boolean
            ipinsrv:
              type: boolean
            animatedmotd:
              type: boolean
            cnameinsrv:
              type: boolean
            cachetime:
              type: integer
          example:
            cachetime: 6
            querymismatch: true
            ipinsrv: true
            ping: true
            srv: true
            query: true
            cnameinsrv: true
            animatedmotd: true
        motd:
          type: object
          properties:
            raw:
              type: array
              items:
                type: string
            clean:
              type: array
              items:
                type: string
            html:
              type: array
              items:
                type: string
          example:
            raw:
            - raw
            - raw
            html:
            - html
            - html
            clean:
            - clean
            - clean
        players:
          type: object
          properties:
            online:
              type: integer
            max:
              type: integer
            sample:
              type: array
              items:
                type: array
                items:
                  type: string
          example:
            max: 5
            online: 1
            sample:
            - - sample
              - sample
            - - sample
              - sample
        version:
          type: string
        protocol:
          type: integer
        hostname:
          type: string
        icon:
          type: string
      example:
        motd:
          raw:
          - raw
          - raw
          html:
          - html
          - html
          clean:
          - clean
          - clean
        protocol: 5
        hostname: hostname
        debug:
          cachetime: 6
          querymismatch: true
          ipinsrv: true
          ping: true
          srv: true
          query: true
          cnameinsrv: true
          animatedmotd: true
        port: 0
        players:
          max: 5
          online: 1
          sample:
          - - sample
            - sample
          - - sample
            - sample
        ip: ip
        icon: icon
        online: true
        version: version
    inline_response_200_1:
      type: object
      properties:
        online:
          type: boolean
        ip:
          type: string
        port:
          type: integer
        debug:
          type: object
          properties:
            ping:
              type: boolean
            query:
              type: boolean
            srv:
              type: boolean
            querymismatch:
              type: boolean
            ipinsrv:
              type: boolean
            cnameinsrv:
              type: boolean
            cachetime:
              type: integer
          example:
            cachetime: 6
            querymismatch: true
            ipinsrv: true
            ping: true
            srv: true
            query: true
            cnameinsrv: true
        motd:
          type: object
          properties:
            raw:
              type: array
              items:
                type: string
            clean:
              type: array
              items:
                type: string
            html:
              type: array
              items:
                type: string
          example:
            raw:
            - raw
            - raw
            html:
            - html
            - html
            clean:
            - clean
            - clean
        players:
          type: object
          properties:
            online:
              type: integer
            max:
              type: integer
            sample:
              type: array
              items:
                type: array
                items:
                  type: string
          example:
            max: 5
            online: 1
            sample:
            - - sample
              - sample
            - - sample
              - sample
        version:
          type: string
        protocol:
          type: integer
        hostname:
          type: string
      example:
        motd:
          raw:
          - raw
          - raw
          html:
          - html
          - html
          clean:
          - clean
          - clean
        protocol: 5
        hostname: hostname
        debug:
          cachetime: 6
          querymismatch: true
          ipinsrv: true
          ping: true
          srv: true
          query: true
          cnameinsrv: true
        port: 0
        players:
          max: 5
          online: 1
          sample:
          - - sample
            - sample
          - - sample
            - sample
        ip: ip
        online: true
        version: version
    inline_response_200_2:
      type: object
      properties:
        account.mojang.com:
          type: string
        api.mojang.com:
          type: string
        authserver.mojang.com:
          type: string
        textures.minecraft.net:
          type: string
        minecraft.net:
          type: string
        sessionserver.mojang.com:
          type: string
      example:
        account.mojang.com: green
        textures.minecraft.net: green
        minecraft.net: green
        api.mojang.com: green
        authserver.mojang.com: green
        sessionserver.mojang.com: green
    inline_response_200_3:
      type: object
      properties:
        trivia:
          type: array
          items:
            type: string
      example:
        trivia:
        - trivia
        - trivia

